version: '3'
services:
  fork:
    image: aztecprotocol/foundry:de33b6af53005037b463318d2628b5cfcaf39916
    pull_policy: always
    entrypoint: 'anvil --silent -p 8545 --host 0.0.0.0 --chain-id 31337'
    expose:
      - '8545'

  p2p-bootstrap:
    image: aztecprotocol/aztec:${AZTEC_DOCKER_TAG:-latest}
    command: 'start --p2p-bootstrap'
    expose:
      - '40400:40400/tcp'
      - '40400:40400/udp'
    environment:
      DEBUG: 'aztec:*'
      DEBUG_COLORS: 1
      P2P_TCP_LISTEN_ADDR: '0.0.0.0:40400'
      P2P_TCP_ANNOUNCE_ADDR: 'p2p-bootstrap:40400'
      P2P_UDP_ANNOUNCE_ADDR: 'p2p-bootstrap:40400'
      PEER_ID_PRIVATE_KEY: '0a260024080112205ea53185db2e52dae74d0d4d6cadc494174810d0a713cd09b0ac517c38bc781e1224080112205ea53185db2e52dae74d0d4d6cadc494174810d0a713cd09b0ac517c38bc781e1a44080112402df8b977f356c6e34fa021c9647973234dff4df706c185794405aafb556723cf5ea53185db2e52dae74d0d4d6cadc494174810d0a713cd09b0ac517c38bc781e'

  end-to-end:
    image: aztecprotocol/end-to-end:${AZTEC_DOCKER_TAG:-latest}
    environment:
      BENCHMARK: true
      DEBUG: ${DEBUG:-'aztec:*'}
      DEBUG_COLORS: 1
      ETHEREUM_HOST: http://fork:8545
      L1_CHAIN_ID: 31337
      ARCHIVER_POLLING_INTERVAL: 500
      P2P_CHECK_INTERVAL: 50
      SEQ_TX_POLLING_INTERVAL: 50
      WS_CHECK_INTERVAL: 50
      SEQ_MAX_TX_PER_BLOCK: 32
      SEQ_MIN_TX_PER_BLOCK: 1
      SEQ_MAX_SECONDS_BETWEEN_BLOCKS: 0
      SEQ_MIN_SECONDS_BETWEEN_BLOCKS: 0
      P2P_TCP_LISTEN_ADDR: '0.0.0.0:40400'
      P2P_NAT_ENABLED: 'false'
      P2P_ENABLED: 'true'
      BOOTSTRAP_NODES: '/ip4/p2p-bootstrap/tcp/40400/p2p/12D3KooWGBpbC6qQFkaCYphjNeY6sV99o4SnEWyTeBigoVriDn4D'
    entrypoint: >
      sh -c '
        while ! nc -z sandbox 8080; do sleep 1; done;
        yarn test ${TEST:-./src/e2e_deploy_contract.test.ts}
      '
    volumes:
      - ../log:/usr/src/yarn-project/end-to-end/log:rw
