[package]
name = "noirc_driver"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noirc_errors.workspace = true
noirc_frontend.workspace = true
noirc_evaluator.workspace = true
noirc_abi.workspace = true
acvm.workspace = true
fm.workspace = true
serde.workspace = true
dirs.workspace = true
