[package]
name = "noirc_errors"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
acvm.workspace = true
codespan-reporting.workspace = true
codespan.workspace = true
fm.workspace = true
noirc_printable_type.workspace = true
serde.workspace = true
serde_with = "3.2.0"
tracing.workspace = true
flate2.workspace = true
serde_json.workspace = true
base64.workspace = true
