name: Nix builds

on:
  push:
    branches:
      - acvm-backend-barretenberg
  workflow_dispatch:

# This will cancel previous runs when a branch or PR is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  nix-build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        target: [default, wasm32, cross-aarch64]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-22.11
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v12
        with:
          name: barretenberg
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Check nix flake
        run: |
          nix flake check

      - name: Build barretenberg as ${{ matrix.target }}
        run: |
          nix build -L .#${{ matrix.target }}

      - name: Prepare artifact
        run: |
          mkdir artifacts
          cp -a ./result/. artifacts
          7z a -ttar -so -an ./artifacts/* | 7z a -si ./libbarretenberg.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: libbarretenberg-${{ runner.os }}-${{ matrix.target }}.tar.gz
          path: ./libbarretenberg.tar.gz
