
hashed_message = [
    0x3a,
    0x73,
    0xf4,
    0x12,
    0x3a,
    0x5c,
    0xd2,
    0x12,
    0x1f,
    0x21,
    0xcd,
    0x7e,
    0x8d,
    0x35,
    0x88,
    0x35,
    0x47,
    0x69,
    0x49,
    0xd0,
    0x35,
    0xd9,
    0xc2,
    0xda,
    0x68,
    0x06,
    0xb4,
    0x63,
    0x3a,
    0xc8,
    0xc1,
    0xe2,
]
pub_key_x = [
    0xa0,
    0x43,
    0x4d,
    0x9e,
    0x47,
    0xf3,
    0xc8,
    0x62,
    0x35,
    0x47,
    0x7c,
    0x7b,
    0x1a,
    0xe6,
    0xae,
    0x5d,
    0x34,
    0x42,
    0xd4,
    0x9b,
    0x19,
    0x43,
    0xc2,
    0xb7,
    0x52,
    0xa6,
    0x8e,
    0x2a,
    0x47,
    0xe2,
    0x47,
    0xc7,
]
pub_key_y = [
    0x89,
    0x3a,
    0xba,
    0x42,
    0x54,
    0x19,
    0xbc,
    0x27,
    0xa3,
    0xb6,
    0xc7,
    0xe6,
    0x93,
    0xa2,
    0x4c,
    0x69,
    0x6f,
    0x79,
    0x4c,
    0x2e,
    0xd8,
    0x77,
    0xa1,
    0x59,
    0x3c,
    0xbe,
    0xe5,
    0x3b,
    0x03,
    0x73,
    0x68,
    0xd7,
]
signature = [
    # r = 0 (first 32 bytes)
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    # s (last 32 bytes - kept from original)
    0x28,
    0x11,
    0x98,
    0x94,
    0x34,
    0x4e,
    0x71,
    0xb7,
    0x87,
    0x70,
    0xcc,
    0x93,
    0x1d,
    0x61,
    0xf4,
    0x80,
    0xec,
    0xbb,
    0x0b,
    0x89,
    0xd6,
    0xeb,
    0x69,
    0x69,
    0x01,
    0x61,
    0xe4,
    0x9a,
    0x71,
    0x5f,
    0xcd,
    0x55,
]
