[package]
name = "noirc_errors"
version = "0.1.0"
authors = ["Kevaundray Wedderburn <kevtheappdev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codespan-reporting = "0.9.5"
codespan = "0.9.5"
fm = {path = "../fm"}
chumsky = { git = "https://github.com/zesterer/chumsky" }
