[package]
name = "token_portal_content_hash_lib"
authors = ["aztec-labs"]
compiler_version = ">=0.18.0"
type = "lib"

[dependencies]
aztec = { path = "../../../../aztec-nr/aztec" }
protocol_types = { path = "../../../../noir-protocol-circuits/src/crates/types" }