version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      # group updates for core GitHub Actions
      core-actions:
        patterns:
          - "actions/**"

  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    # Check the npm registry for updates every Monday
    schedule:
      interval: "weekly"
