[package]
name = "noirc_abi"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
acvm.workspace = true
iter-extended.workspace = true
noirc_printable_type.workspace = true
toml.workspace = true
serde_json = "1.0"
serde.workspace = true
thiserror.workspace = true
num-bigint = "0.4"
num-traits = "0.2"

[dev-dependencies]
strum.workspace = true
strum_macros.workspace = true
proptest.workspace = true
proptest-derive.workspace = true

[features]
bn254 = ["acvm/bn254"]
bls12_381 = ["acvm/bls12_381"]
