

# hashed_msg = secp256k1 ORDER
[[invalid_signatures]]
message_hash = [
    0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xfe,
    0xba, 0xae, 0xdc, 0xe6, 0xaf, 0x48, 0xa0, 0x3b, 0xbf, 0xd2, 0x5e, 0x8c, 0xd0, 0x36, 0x41, 0x41,
]
pub_key_x = [
    0xa0, 0x43, 0x4d, 0x9e, 0x47, 0xf3, 0xc8, 0x62, 0x35, 0x47, 0x7c, 0x7b, 0x1a, 0xe6, 0xae, 0x5d, 
    0x34, 0x42, 0xd4, 0x9b, 0x19, 0x43, 0xc2, 0xb7, 0x52, 0xa6, 0x8e, 0x2a, 0x47, 0xe2, 0x47, 0xc7,
]
pub_key_y = [
    0x89, 0x3a, 0xba, 0x42, 0x54, 0x19, 0xbc, 0x27, 0xa3, 0xb6, 0xc7, 0xe6, 0x93, 0xa2, 0x4c, 0x69,
    0x6f, 0x79, 0x4c, 0x2e, 0xd8, 0x77, 0xa1, 0x59, 0x3c, 0xbe, 0xe5, 0x3b, 0x03, 0x73, 0x68, 0xd7,
]
signature = [
    0xe5, 0x08, 0x1c, 0x80, 0xab, 0x42, 0x7d, 0xc3, 0x70, 0x34, 0x6f, 0x4a, 0x0e, 0x31, 0xaa, 0x2b,
    0xad, 0x8d, 0x97, 0x98, 0xc3, 0x80, 0x61, 0xdb, 0x9a, 0xe5, 0x5a, 0x4e, 0x8d, 0xf4, 0x54, 0xfd,
    0x28, 0x11, 0x98, 0x94, 0x34, 0x4e, 0x71, 0xb7, 0x87, 0x70, 0xcc, 0x93, 0x1d, 0x61, 0xf4, 0x80,
    0xec, 0xbb, 0x0b, 0x89, 0xd6, 0xeb, 0x69, 0x69, 0x01, 0x61, 0xe4, 0x9a, 0x71, 0x5f, 0xcd, 0x55,
]

# R.x >= curve order
# signature is r = s = 1 and message hash = 1
# in ecdsa verification, u1 and u2 are 1, so R = G (generator) + P (pubkey)
# P is chosen so that P = R - G, with R.x = curve's field modulus - 3
[[invalid_signatures]]
message_hash = [
    # hashed_msg = 1
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01,
]
pub_key_x = [
    0x23, 0xc9, 0x60, 0x0e, 0x95, 0x68, 0x57, 0x47,
    0xe8, 0x9d, 0xcb, 0x90, 0x5b, 0xff, 0xf5, 0xa1,
    0x5c, 0x77, 0xc0, 0x3a, 0x2e, 0x29, 0x73, 0x41,
    0x6e, 0x36, 0xd4, 0x73, 0xe9, 0xce, 0x9f, 0x72,
]
pub_key_y = [
    0x6b, 0x55, 0x85, 0x03, 0xba, 0xda, 0xf0, 0x27,
    0x6c, 0x4e, 0x01, 0xdc, 0x70, 0xe3, 0x0c, 0x13,
    0x2b, 0x35, 0xe8, 0xc2, 0x25, 0x0d, 0xe8, 0xa3,
    0xc0, 0xbd, 0x2a, 0xe4, 0x51, 0xe9, 0xb7, 0xda,
]
signature =  [
    # r = 1 (bytes 0..32, big-endian)
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01,
    # s = 1 (bytes 32..64, big-endian)
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01,
]

# R is point at infinity (from https://gist.github.com/guidovranken/5d7c2f9d2432047bd8292993fd785cbe)
[[invalid_signatures]]
message_hash = [
        0xb6, 0xb8, 0x18, 0x2e, 0xc7, 0x1f, 0x95, 0xd4, 0x42, 0x13, 0x3f, 0x21, 0x5c, 0x9e, 0x0e, 0x7b,
        0x55, 0x98, 0x0e, 0xf2, 0x02, 0x07, 0xf7, 0xaa, 0x2a, 0xbb, 0x7a, 0x7e, 0xe9, 0x1b, 0xab, 0x1f
]
pub_key_x = [
        0x2f, 0x8b, 0xde, 0x4d, 0x1a, 0x07, 0x20, 0x93, 0x55, 0xb4, 0xa7, 0x25, 0x0a, 0x5c, 0x51, 0x28,
        0xe8, 0x8b, 0x84, 0xbd, 0xdc, 0x61, 0x9a, 0xb7, 0xcb, 0xa8, 0xd5, 0x69, 0xb2, 0x40, 0xef, 0xe4
]
pub_key_y = [
        0xd8, 0xac, 0x22, 0x26, 0x36, 0xe5, 0xe3, 0xd6, 0xd4, 0xdb, 0xa9, 0xdd, 0xa6, 0xc9, 0xc4, 0x26,
        0xf7, 0x88, 0x27, 0x1b, 0xab, 0x0d, 0x68, 0x40, 0xdc, 0xa8, 0x7d, 0x3a, 0xa6, 0xac, 0x62, 0xd6
]
signature =  [
        0xa8, 0x41, 0x94, 0xc3, 0x71, 0xc6, 0x7b, 0xa2, 0x59, 0x2f, 0x59, 0xc6, 0x20, 0xad, 0x30, 0x4c,
        0xb7, 0x6d, 0x7a, 0x88, 0x25, 0x6b, 0xb5, 0x0d, 0xc4, 0x1c, 0x66, 0x57, 0x44, 0xbf, 0x78, 0x61,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x64,
]
