name: aztec-devnet
services:
  pxe:
    image: aztecprotocol/aztec${AZTEC_DOCKER_TAG:-@sha256:e101ddc5ec24fc2c52af0e13b9005329d388481d9ccbf07289bdd62faba44615}
    # need to run bb for proofs and bb is only built for x86
    platform: linux/amd64
    environment:
      LOG_LEVEL: info
      DEBUG: aztec:*
      DEBUG_COLORS: 1
      CHAIN_ID: 31337
      VERSION: 1
      PXE_PROVER_ENABLED: ${PXE_PROVER_ENABLED:-1}
      PXE_DATA_DIRECTORY: /var/lib/aztec/pxe
      NODE_NO_WARNINGS: 1
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "export AZTEC_NODE_URL=$$(cat /var/run/secrets/aztec-node-url); node /usr/src/yarn-project/aztec/dest/bin/index.js start --pxe",
      ]
    secrets:
      - aztec-node-url
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - aztec-pxe:/var/lib/aztec/pxe
  cli:
    image: aztecprotocol/aztec${AZTEC_DOCKER_TAG:-@sha256:e101ddc5ec24fc2c52af0e13b9005329d388481d9ccbf07289bdd62faba44615}
    # run the same image as pxe
    platform: linux/amd64
    environment:
      PXE_URL: http://pxe:8080
      NODE_NO_WARNINGS: 1
      PRIVATE_KEY:
      ETHEREUM_HOST:
    entrypoint: ["node", "/usr/src/yarn-project/cli/dest/bin/index.js"]
    profiles:
      - cli

secrets:
  aztec-node-url:
    environment: AZTEC_NODE_URL
