[package]
name = "doc-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.12"
clap = { version = "3.2.0", features = ["derive", "cargo"] }
noirc_frontend = { path = "../../compiler/noirc_frontend" }
