[package]
name = "rollup_lib"
type = "lib"
authors = [""]
compiler_version = ">=0.18.0"

[dependencies]
bigint = { tag = "v0.7.1", git = "https://github.com/noir-lang/noir-bignum" }
types = { path = "../types" }
blob = { path = "../blob" }
poseidon = { tag = "v0.1.0", git = "https://github.com/noir-lang/poseidon" }
