[package]
name = "benchmarking_contract"
authors = [""]
compiler_version = "0.1"
type = "contract"

[dependencies]
aztec = { path = "../../../../aztec-nr/aztec" }
value_note = { path = "../../../../aztec-nr/value-note" }
