[package]
name = "bb-pil-backend"
version = "0.1.0"
authors = ["Aztec Labs"]
edition = "2021"

[dependencies]
num-bigint = "0.4.3"

powdr-number = { path = "../powdr/number" }
num-traits = "0.2.15"
num-integer = "0.1.45"
itertools = "^0.10"
log = "0.4.17"
rand = "0.8.5"
powdr-ast = { path = "../powdr/ast" }
handlebars = { version = "5.1.2", features = ["string_helpers"] }
serde_json = "1.0.120"
