[package]
name = "backend-interface"
description = "The definition of the backend CLI interface which Nargo uses for proving/verifying ACIR circuits."
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
acvm.workspace = true
dirs.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
bb_abstraction_leaks.workspace = true
tracing.workspace = true

tempfile.workspace = true

## bb binary downloading
tar = "~0.4.15"
flate2 = "~1.0.1"
reqwest = { version = "0.11.20", default-features = false, features = [
    "rustls-tls",
    "blocking",
] }

[dev-dependencies]
test-binary = "3.0.1"

[build-dependencies]
build-target = "0.4.0"
const_format.workspace = true
