[package]
name = "noir_ssa_cli"
description = "CLI tool to work with SSA independently of any Noir program"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "noir-ssa"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
base64.workspace = true
clap.workspace = true
color-eyre.workspace = true
const_format.workspace = true
serde_json.workspace = true
thiserror.workspace = true
toml.workspace = true
tempfile.workspace = true
tracing-subscriber.workspace = true

# Noir repo dependencies
noir_artifact_cli.workspace = true
noir_ast_fuzzer.workspace = true
noirc_abi.workspace = true
noirc_driver.workspace = true
noirc_evaluator.workspace = true
noirc_errors.workspace = true
iter-extended.workspace = true
