[package]
name = "token_blacklist_contract"
authors = [""]
compiler_version = ">=0.18.0"
type = "contract"

[dependencies]
aztec = { path = "../../../aztec-nr/aztec" }
safe_math = { path = "../../../aztec-nr/safe-math" }
field_note = { path = "../../../aztec-nr/field-note" }
authwit = { path = "../../../aztec-nr/authwit" }
protocol_types = { path = "../../../noir-protocol-circuits/src/crates/types" }