# Random test key
priv_key = "0x000000000000000000000000000000000000000000000000000000616c696365"
note_root = "0x02278fc806225cd696bd502049f7bb98624536de56d09343f8a26ac1876b23a0"
index = "0"
note_hash_path = [
    "0x1cdcf02431ba623767fe389337d011df1048dcc24b98ed81cec97627bab454a0",
    "0x0b5e9666e7323ce925c28201a97ddf4144ac9d148448ed6f49f9008719c1b85b",
    "0x22ec636f8ad30ef78c42b7fe2be4a4cacf5a445cfb5948224539f59a11d70775",
]
to_pubkey_x = "0x0000000000000000000000000000000000000000000000000000000000000001"
to_pubkey_y = "0x0000000000000002cf135e7506a45d632d270d45f1181294833fc48d823f272c"
return = [
    "0x2b3e2281b493baa4497aa5fe5abf9f340f43bd9c4a65dcb1cda20dc210058870",
    "0x1e2d117a1b344bd3ff0cf1d5f860f02cd8b27f6b8ccd2e844852f2c93d36f4aa",
]
