[package]
name = "acir"
version = "0.1.0"
authors = ["Kevaundray Wedderburn <kevtheappdev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noir_field = { path = "../noir_field", default-features = false }
indexmap = "1.7.0"
serde = { version = "1.0.136", features = ["derive"] }
rmp-serde = "1.1.0"
flate2 = "1.0.24"

[dev-dependencies]
serde_json = "1.0"
