[workspace]
members = [
    "crates/types",
    "crates/private-kernel-lib",
    "crates/private-kernel-init",
    "crates/private-kernel-init-simulated",
    "crates/private-kernel-inner",
    "crates/private-kernel-inner-simulated",
    "crates/private-kernel-ordering",
    "crates/private-kernel-ordering-simulated",
    "crates/public-kernel-lib",
    "crates/public-kernel-private-previous",
    "crates/public-kernel-private-previous-simulated",
    "crates/public-kernel-public-previous",
    "crates/public-kernel-public-previous-simulated",
    "crates/rollup-lib",
    "crates/rollup-merge",
    "crates/rollup-base",
    "crates/rollup-base-simulated",
    "crates/rollup-root",
]
