to_hash = [[1,5,9,2,24,563,3545,5,52,4244,43,2,7373567,2,286762,7,2457,24,2456,2456],
[2234,2,26,27,24566,132452,3452456344567,657,45674657,4567467,45674,4567456,4567,23454,2345,2345345245,25252345,2435234524366,8678678,67867567],
[9887575467567,5367367243617,46244567783,64673425,67456573456,4673457,46735,745674,6574,567456,7456,84,683,683,8368,38,32,16,7,98],
#[465656,234324,4353,5245246,2567345674567,5634563456,7676474,4747,4567456746,56,4657456,4657,4567,46,7,8,98,87,76,57]
]
enable = [1,1,0]
return = ["0x2123044e00a868c5828caa3e81bf44ce1131856159853283118b979cd9ef0357", "0x25e65fbbdb68f3be5112b437f6179523e4817ba6c875817d19ee6b4d654d0823", "0x00"]
