[package]
name = "public_kernel_app_logic"
type = "bin"
authors = [""]
compiler_version = ">=0.18.0"

[dependencies]
types = { path = "../types" }
public_kernel_lib = { path = "../public-kernel-lib" }
