[package]
name = "noir_ssa_executor"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[package.metadata]
cargo-fuzz = true

[lints]
workspace = true

[dependencies]
noirc_errors.workspace = true
noirc_evaluator.workspace = true
noirc_frontend.workspace = true
noirc_driver.workspace = true
noirc_abi.workspace = true
acvm.workspace = true
bn254_blackbox_solver.workspace = true
thiserror.workspace = true
nargo.workspace = true
base64.workspace = true

[features]
nargo = ["nargo/rpc"]
bls12_381 = []

[[example]]
name = "compilation"
path = "examples/compilation.rs"