[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.23"

remappings = [
  "@oz/=lib/openzeppelin-contracts/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

fs_permissions = [
  {access = "read", path = "./test/fixtures/mixed_block_0.json"},
  {access = "read", path = "./test/fixtures/mixed_block_1.json"},
  {access = "read", path = "./test/fixtures/empty_block_0.json"},
  {access = "read", path = "./test/fixtures/empty_block_1.json"},
]

[fmt]
line_length = 100
tab_width = 2
variable_override_spacing=false

[rpc_endpoints]
mainnet_fork="https://mainnet.infura.io/v3/9928b52099854248b3a096be07a6b23c"

