[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.21"

remappings = [
  "@oz/=lib/openzeppelin-contracts/contracts/",
  "@aztec/core/=src/core/",
  "@aztec/periphery/=src/periphery/",
  "@aztec/mock/=src/mock/",
  "@aztec/verifier/=lib/aztec-verifier-contracts/src/"
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[fmt]
line_length = 100
tab_width = 2
variable_override_spacing=false

[rpc_endpoints]
mainnet_fork="https://mainnet.infura.io/v3/9928b52099854248b3a096be07a6b23c"