[package]
name = "non_native_token_contract"
authors = [""]
compiler_version = "0.1"
type = "bin"

[dependencies]
aztec = { path = "../../../../noir-libs/noir-aztec" }
value_note = { path = "../../../../noir-libs/value-note"}