arr = [
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    2, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    3, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    4, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    5, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    6, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    7, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    8, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    9, 2, 3, 4, 5, 6, 7, 8, 9, 10,
   10, 2, 3, 4, 5, 6, 7, 8, 9, 10,

    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    2, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    3, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    4, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    5, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    6, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    7, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    8, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    9, 2, 3, 4, 5, 6, 7, 8, 9, 10,
   10, 2, 3, 4, 5, 6, 7, 8, 9, 10,

    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    2, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    3, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    4, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    5, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    6, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    7, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    8, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    9, 2, 3, 4, 5, 6, 7, 8, 9, 10,
   10, 2, 3, 4, 5, 6, 7, 8, 9, 10,
]
