[package]
name = "slow_tree_contract"
authors = [""]
compiler_version = ">=0.18.0"
type = "contract"

[dependencies]
aztec = { path = "../../../../aztec-nr/aztec" }
value_note = { path = "../../../../aztec-nr/value-note"}
slow_updates_tree = { path = "../../../../aztec-nr/slow-updates-tree"}
protocol_types = { path = "../../../../noir-protocol-circuits/src/crates/types" }