[package]
name = "recurse_node"
type = "bin"
authors = [""]
compiler_version = ">=0.26.0"

[dependencies]
bb_proof_verification = { tag = "v3.0.0-nightly.20251104", git = "https://github.com/aztecprotocol/aztec-packages", directory = "./barretenberg/noir/bb_proof_verification" }
