[package]
name = "address_note"
authors = ["aztec-labs"]
compiler_version = ">=0.18.0"
type = "lib"

[dependencies]
aztec = { path = "../aztec" }
protocol_types = { path = "../../../../noir-protocol-circuits/src/crates/types" }