[package]
name = "noirc_artifacts"
description = "Definitions of Nargo's build artifacts"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fm.workspace = true
noirc_abi.workspace = true
noirc_driver.workspace = true
noirc_errors.workspace = true
noirc_printable_type.workspace = true
serde.workspace = true
codespan-reporting.workspace = true


[dev-dependencies]
tempfile.workspace = true
