
        # Manually copied from merkle.rs (test::basic_interop_update) 
        leaf = "0x06c2335d6f7acb84bbc7d0892cefebb7ca31169a89024f24814d5785e0d05324"
        index = "0x0000000000000000000000000000000000000000000000000000000000000002"
        root = "0x241fc8d893854e78dd2d427e534357fe02279f209193f0f82e13a3fd4e15375e"
        hashpath = [
                "0x06c2335d6f7acb84bbc7d0892cefebb7ca31169a89024f24814d5785e0d05324",
                "0x12dc36b01cbd8a6248b04e08f0ec91aa6d11a91f030b4a7b1460281859942185",
                "0x2a57882283ba48c2e523fbf8142c0867e82cfaba2410793d3331a9c685f40790",
                "0x145beb7dcd00d8eee922af3fee2b002c6e56b716630752b787acfbe685769040",
                "0x20a7f69fa7eada3e900b803301074386ef2ea8be29f3aa943eefc3654c0a94e6",
                "0x073b84f35922842dcf4c10596c3fe3eab7e61939120d2aca0a531e4e6fdce22b"
                ]