[package]
name = "recursion"
type = "bin"
authors = [""]

[dependencies]
bb_proof_verification = {  git = "https://github.com/AztecProtocol/aztec-packages", tag = "v4.0.0-nightly.20260120", directory = "./barretenberg/noir/bb_proof_verification" }
