[package]
name = "nargo_toml"
description = "Utilities for working with Nargo.toml files"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs.workspace = true
fm.workspace = true
nargo.workspace = true
noirc_frontend.workspace = true
serde.workspace = true
thiserror.workspace = true
toml.workspace = true
url.workspace = true
noirc_driver.workspace = true
semver = "1.0.20"

[dev-dependencies]
tempfile.workspace = true
test-case.workspace = true
