[package]
name = "pokeable_token_contract"
authors = [""]
compiler_version = "0.1"
type = "contract"

[dependencies]
aztec = { path = "../../../../noir-libs/noir-aztec" }
value_note = { path = "../../../../noir-libs/value-note"}