[package]
name = "nargo_cli"
description = "Noir's package manager"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Rename binary from `nargo_cli` to `nargo`
[[bin]]
name = "nargo"
path = "src/main.rs"

[build-dependencies]
rustc_version = "0.4.0"
build-data.workspace = true
toml.workspace = true

[dependencies]
clap.workspace = true
fm.workspace = true
iter-extended.workspace = true
nargo.workspace = true
nargo_fmt.workspace = true
nargo_toml.workspace = true
noir_lsp.workspace = true
noir_debugger.workspace = true
noirc_driver.workspace = true
noirc_frontend.workspace = true
noirc_abi.workspace = true
noirc_errors.workspace = true
acvm.workspace = true
bn254_blackbox_solver.workspace = true
toml.workspace = true
serde.workspace = true
serde_json.workspace = true
prettytable-rs = "0.10"
rayon = "1.8.0"
thiserror.workspace = true
tower.workspace = true
async-lsp = { workspace = true, features = ["client-monitor", "stdio", "tracing", "tokio"] }
const_format.workspace = true
hex.workspace = true
similar-asserts.workspace = true
termcolor = "1.1.2"
color-eyre = "0.6.2"
tokio = { version = "1.0", features = ["io-std"] }
dap.workspace = true

# Backends
backend-interface = { path = "../backend_interface" }

# Logs
tracing-subscriber.workspace = true
tracing-appender = "0.2.3"

[target.'cfg(not(unix))'.dependencies]
tokio-util = { version = "0.7.8", features = ["compat"] }

[dev-dependencies]
tempfile.workspace = true
dirs.workspace = true
assert_cmd = "2.0.8"
assert_fs = "1.0.10"
predicates = "2.1.5"
fm.workspace = true
criterion = "0.5.0"
paste = "1.0.14"
pprof = { version = "0.12", features = [
    "flamegraph",
    "frame-pointer",
    "criterion",
] }
iai = "0.1.1"
test-binary = "3.0.2"

[[bench]]
name = "criterion"
harness = false

[[bench]]
name = "iai"
harness = false
