[workspace]
members = [
    "src/contracts/benchmarking_contract", 
    "src/contracts/card_game_contract", 
    "src/contracts/child_contract", 
    "src/contracts/docs_example_contract",
    "src/contracts/easy_private_token_contract",
    "src/contracts/ecdsa_account_contract",
    "src/contracts/escrow_contract",
    "src/contracts/import_test_contract",
    "src/contracts/lending_contract",
    "src/contracts/multi_transfer_contract",
    "src/contracts/parent_contract",
    "src/contracts/pending_commitments_contract",
    "src/contracts/pokeable_token_contract",
    "src/contracts/price_feed_contract",
    "src/contracts/private_token_airdrop_contract",
    "src/contracts/private_token_contract",
    "src/contracts/public_token_contract",
    "src/contracts/schnorr_account_contract",
    "src/contracts/schnorr_hardcoded_account_contract",
    "src/contracts/schnorr_single_key_account_contract",
    "src/contracts/stateful_test_contract",
    "src/contracts/test_contract",
    "src/contracts/token_contract",
    "src/contracts/token_bridge_contract",
    "src/contracts/uniswap_contract",
]
