[package]
name = "acvm"
version = "0.1.0"
authors = ["Kevaundray Wedderburn <kevtheappdev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4"
num-traits = "0.2"
acir = { path = "../acir" }

# Ideally, there should be a way for the Nargo.toml file to indicate a proof system
# and not need to pull in the other proof systems. Also ideally like to avoid using DLL
# It seems to be only way... This is not an immediate problem while dependencies are small
aztec_backend = { optional = true, path = "../aztec_backend" }
arkworks_backend = { optional = true, git = "https://github.com/noir-lang/arkworks_backend" }
sled = "0.34.6"
noir_field = { path = "../noir_field" }
sha2 = "0.9.3"
blake2 = "0.9.1"
hex = "0.4.2"
cfg-if = "1.0.0"
k256 = { version = "0.7.2", features = [
    "ecdsa",
    "ecdsa-core",
    "sha256",
    "digest",
    "arithmetic",
] }
indexmap = "1.7.0"

[features]

plonk = ["aztec_backend"]
marlin = ["arkworks_backend"]

[dev-dependencies]
tempfile = "3.2.0"
