[package]
name = "gas_token_contract"
authors = [""]
compiler_version = ">=0.25.0"
type = "contract"

[dependencies]
aztec = { path = "../../../aztec-nr/aztec" }
authwit = { path = "../../../aztec-nr/authwit" }
deployer = { path = "../contract_instance_deployer_contract" }
registerer = { path = "../contract_class_registerer_contract" }