# all combinations of the low 4 bits, i.e. 0000xxxx in binary
x1 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12,13,14,15]
y1 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12,13,14,15]
# all combinations of the high 4 bits, i.e. xxxx0000 in binary
x2 = ["-128","-112","-96","-80","-64","-48","-32","-16",0,16,32,48,64,80,96,112]
y2 = ["-128","-112","-96","-80","-64","-48","-32","-16",0,16,32,48,64,80,96,112]
# all combinations of the high 2 bits + low 2 bits, i.e. xx0000xx in binary
x3 = ["-128","-127","-126","-125","-64","-63","-62","-61",0,1,2,3,64,65,66,67]
y3 = ["-128","-127","-126","-125","-64","-63","-62","-61",0,1,2,3,64,65,66,67]
# random numbers
x4 = ["-126","-123","-107","-106","-90","-80","-37","-33","-23","-6",25,42,45,56,101,108]
y4 = ["-126","-123","-107","-106","-90","-80","-37","-33","-23","-6",25,42,45,56,101,108]

z = [
    [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
]
