old_root = "0x2131c74af6250d1246797588ff075b672e3d2e6805f9c6b313ade8f6b9e12802"
old_leaf = "0x2df8b940e5890e4e1377e05373fae69a1d754f6935e6a780b666947431f2cdcd"
old_hash_path = [
    "0x03542cb720369f19a74fd05b4edfbedb27a78514ad3283f1b3270a1656cced8e",
    "0x1278272f6e617666b18c52349c4bbe94249a8ab59add2ee0a142168a92b7ffc2",
    "0x2547cfd7699ad1f331fb77b30a3445c6043a4c62b5b1215356b2924607bf937b",
]
new_root = "0x25e2a8ee5b85e5b546ae27832b9b53f5fae5b371e3e7f8cddda839f41669fc68"
leaf = "0x23fe6c8f2426b793f0f156f57efbecbea52e951af761634a85e80cc1a9fb5003"
index = "0"
