[package]
name = "semaphore_depth_10"
type = "bin"
authors = [""]

[dependencies]
ec = { git = "https://github.com/noir-lang/noir-edwards", tag = "v0.2.5" }
poseidon = { git = "https://github.com/noir-lang/poseidon", tag = "v0.1.1" }
