[package]
name = "noirc_abi"
version = "0.1.0"
authors = ["Kevaundray Wedderburn <kevtheappdev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
acvm = { git = "https://github.com/noir-lang/noir" }
iter-extended= { path = "../iter-extended" }
toml = "0.5.8"
serde = { version = "1.0.136", features = ["derive"] }
serde_derive = "1.0.136"
blake2 = "0.9.1"

[dev-dependencies]
serde_json = "1.0"
