[package]
name = "noirc_frontend"
version = "0.1.0"
authors = ["Kevaundray Wedderburn <kevtheappdev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noir_field = {path = "../noir_field"}
acvm = {path = "../acvm"}
noirc_abi = {path = "../noirc_abi"}
noirc_errors = {path = "../noirc_errors"}
std_lib = {path = "../std_lib"}
fm = {path = "../fm"}
arena = {path = "../arena"}

thiserror = "1.0.21"
pathdiff = "0.2"
smol_str = "0.1.17"
rustc-hash = "1.1.0"