[package]
name = "acvm-backend-barretenberg"
description = "An ACVM backend which allows proving/verifying ACIR circuits against Aztec Lab's Barretenberg library."
version = "0.11.0"
authors.workspace = true
edition.workspace = true
rust-version = "1.66"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
acvm.workspace = true
dirs.workspace = true
thiserror.workspace = true
base64.workspace = true
serde.workspace = true
serde_json.workspace = true

tempfile = "3.6.0"

## bb binary downloading
const_format = "0.2.30"
tar = "~0.4.15"
flate2 = "~1.0.1"
reqwest = { version = "0.11.16", default-features = false, features = [
    "rustls-tls",
    "blocking",
] }

[dev-dependencies]
serial_test = "2.0.0"
test-binary = "3.0.1"

[build-dependencies]
build-target = "0.4.0"
