[package]
name = "noir_lsp"
description = "Language server for Noir"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
acvm.workspace = true
codespan-lsp.workspace = true
lsp-types.workspace = true
nargo = { workspace = true, features = ["rpc"] }
nargo_fmt.workspace = true
nargo_toml.workspace = true
noirc_driver.workspace = true
noirc_errors.workspace = true
noirc_frontend.workspace = true
serde.workspace = true
serde_json.workspace = true
strum = "0.24"
tower.workspace = true
async-lsp = { workspace = true, features = ["omni-trait"] }
thiserror.workspace = true
fm.workspace = true
rayon.workspace = true
fxhash.workspace = true
convert_case = "0.6.0"

[target.'cfg(all(target_arch = "wasm32", not(target_os = "wasi")))'.dependencies]
wasm-bindgen.workspace = true

[dev-dependencies]
tokio = { version = "1.0", features = ["macros", "rt"] }
