[package]
name = "poseidonsponge_x5_254"
description = "Variable-length Poseidon-128 sponge test on 7 elements with alpha = 5"
type = "bin"
authors = [""]

[dependencies]
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }
