[package]
name = "noirc_driver"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
build-data.workspace = true

[dependencies]
clap.workspace = true
noirc_errors.workspace = true
noirc_frontend.workspace = true
noirc_evaluator.workspace = true
noirc_abi.workspace = true
acvm.workspace = true
iter-extended.workspace = true
fm.workspace = true
serde.workspace = true
fxhash.workspace = true
rust-embed.workspace = true
tracing.workspace = true

[features]
bn254 = ["noirc_frontend/bn254", "noirc_evaluator/bn254"]
bls12_381 = ["noirc_frontend/bls12_381", "noirc_evaluator/bls12_381"]
