[package]
name = "noir_wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
crate-type = ["cdylib"]

[dependencies]
# Compile with bn254 field as a default for now
acvm = { path = "../acvm", features = ["bn254"] }
noirc_driver = { path = "../noirc_driver", default-features = false, features = [
    "wasm",
] }

console_error_panic_hook = "*"

wasm-bindgen = { version = "*", features = ["serde-serialize"] }

getrandom = { version = "0.2.4", features = ["js"] }
js-sys = "0.3.55"

[dev-dependencies]
wasm-bindgen-test = "*"
