[package]
name = "noir_wasm"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
crate-type = ["cdylib"]

[dependencies]
# Compile with bn254 field as a default for now
acvm = { path = "../acvm", features = ["bn254"] }
noirc_driver = { path = "../noirc_driver", features = ["wasm"] }

console_error_panic_hook.workspace = true

wasm-bindgen.workspace = true
gloo-utils.workspace = true

getrandom.workspace = true
js-sys.workspace = true

[dev-dependencies]
wasm-bindgen-test.workspace = true
