[workspace]
members = [
    "contracts/app_subscription_contract",
    "contracts/avm_initializer_test_contract",
    "contracts/avm_test_contract",
    "contracts/fpc_contract",
    "contracts/benchmarking_contract",
    "contracts/card_game_contract",
    "contracts/child_contract",
    "contracts/claim_contract",
    "contracts/contract_class_registerer_contract",
    "contracts/contract_instance_deployer_contract",
    "contracts/counter_contract",
    "contracts/crowdfunding_contract",
    "contracts/delegator_contract",
    "contracts/delegated_on_contract",
    "contracts/docs_example_contract",
    "contracts/easy_private_token_contract",
    "contracts/easy_private_voting_contract",
    "contracts/ecdsa_account_contract",
    "contracts/escrow_contract",
    "contracts/gas_token_contract",
    "contracts/import_test_contract",
    "contracts/inclusion_proofs_contract",
    "contracts/lending_contract",
    "contracts/parent_contract",
    "contracts/pending_note_hashes_contract",
    "contracts/price_feed_contract",
    "contracts/schnorr_account_contract",
    "contracts/schnorr_hardcoded_account_contract",
    "contracts/schnorr_single_key_account_contract",
    "contracts/slow_tree_contract",
    "contracts/stateful_test_contract",
    "contracts/test_contract",
    "contracts/token_contract",
    "contracts/token_blacklist_contract",
    "contracts/token_bridge_contract",
    "contracts/uniswap_contract",
    "contracts/reader_contract",
    "contracts/multi_call_entrypoint_contract",
]
