
hashed_message = [
    0x3a,
    0x73,
    0xf4,
    0x12,
    0x3a,
    0x5c,
    0xd2,
    0x12,
    0x1f,
    0x21,
    0xcd,
    0x7e,
    0x8d,
    0x35,
    0x88,
    0x35,
    0x47,
    0x69,
    0x49,
    0xd0,
    0x35,
    0xd9,
    0xc2,
    0xda,
    0x68,
    0x06,
    0xb4,
    0x63,
    0x3a,
    0xc8,
    0xc1,
    0xe2,
]
pub_key_x = [
    # Invalid public key - not on the curve
    0x01,
    0x02,
    0x03,
    0x04,
    0x05,
    0x06,
    0x07,
    0x08,
    0x09,
    0x0a,
    0x0b,
    0x0c,
    0x0d,
    0x0e,
    0x0f,
    0x10,
    0x11,
    0x12,
    0x13,
    0x14,
    0x15,
    0x16,
    0x17,
    0x18,
    0x19,
    0x1a,
    0x1b,
    0x1c,
    0x1d,
    0x1e,
    0x1f,
    0x20,
]
pub_key_y = [
    0x21,
    0x22,
    0x23,
    0x24,
    0x25,
    0x26,
    0x27,
    0x28,
    0x29,
    0x2a,
    0x2b,
    0x2c,
    0x2d,
    0x2e,
    0x2f,
    0x30,
    0x31,
    0x32,
    0x33,
    0x34,
    0x35,
    0x36,
    0x37,
    0x38,
    0x39,
    0x3a,
    0x3b,
    0x3c,
    0x3d,
    0x3e,
    0x3f,
    0x40,
]
signature = [
    0xe5,
    0x08,
    0x1c,
    0x80,
    0xab,
    0x42,
    0x7d,
    0xc3,
    0x70,
    0x34,
    0x6f,
    0x4a,
    0x0e,
    0x31,
    0xaa,
    0x2b,
    0xad,
    0x8d,
    0x97,
    0x98,
    0xc3,
    0x80,
    0x61,
    0xdb,
    0x9a,
    0xe5,
    0x5a,
    0x4e,
    0x8d,
    0xf4,
    0x54,
    0xfd,
    0x28,
    0x11,
    0x98,
    0x94,
    0x34,
    0x4e,
    0x71,
    0xb7,
    0x87,
    0x70,
    0xcc,
    0x93,
    0x1d,
    0x61,
    0xf4,
    0x80,
    0xec,
    0xbb,
    0x0b,
    0x89,
    0xd6,
    0xeb,
    0x69,
    0x69,
    0x01,
    0x61,
    0xe4,
    0x9a,
    0x71,
    0x5f,
    0xcd,
    0x55,
]
