[kernel_data]
encrypted_logs_hash = [
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
]
new_commitments = [
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
]
new_l2_to_l1_msgs = [
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
]
new_nullifiers = [
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
]
unencrypted_logs_hash = [
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x0000000000000000000000000000000000000000000000000000000000000000",
]

[[kernel_data.new_contracts]]
contract_address = "0x0000000000000000000000000000000000000000000000000000000000000000"
portal_contract_address = "0x0000000000000000000000000000000000000000000000000000000000000000"

[[kernel_data.public_data_update_requests]]
leaf_slot = "0x0000000000000000000000000000000000000000000000000000000000000000"
new_value = "0x0000000000000000000000000000000000000000000000000000000000000000"
old_value = "0x0000000000000000000000000000000000000000000000000000000000000000"

[[kernel_data.public_data_update_requests]]
leaf_slot = "0x0000000000000000000000000000000000000000000000000000000000000000"
new_value = "0x0000000000000000000000000000000000000000000000000000000000000000"
old_value = "0x0000000000000000000000000000000000000000000000000000000000000000"

[[kernel_data.public_data_update_requests]]
leaf_slot = "0x0000000000000000000000000000000000000000000000000000000000000000"
new_value = "0x0000000000000000000000000000000000000000000000000000000000000000"
old_value = "0x0000000000000000000000000000000000000000000000000000000000000000"

[[kernel_data.public_data_update_requests]]
leaf_slot = "0x0000000000000000000000000000000000000000000000000000000000000000"
new_value = "0x0000000000000000000000000000000000000000000000000000000000000000"
old_value = "0x0000000000000000000000000000000000000000000000000000000000000000"

[[kernel_data.public_data_update_requests]]
leaf_slot = "0x0000000000000000000000000000000000000000000000000000000000000000"
new_value = "0x0000000000000000000000000000000000000000000000000000000000000000"
old_value = "0x0000000000000000000000000000000000000000000000000000000000000000"

[[kernel_data.public_data_update_requests]]
leaf_slot = "0x0000000000000000000000000000000000000000000000000000000000000000"
new_value = "0x0000000000000000000000000000000000000000000000000000000000000000"
old_value = "0x0000000000000000000000000000000000000000000000000000000000000000"

[[kernel_data.public_data_update_requests]]
leaf_slot = "0x0000000000000000000000000000000000000000000000000000000000000000"
new_value = "0x0000000000000000000000000000000000000000000000000000000000000000"
old_value = "0x0000000000000000000000000000000000000000000000000000000000000000"

[[kernel_data.public_data_update_requests]]
leaf_slot = "0x0000000000000000000000000000000000000000000000000000000000000000"
new_value = "0x0000000000000000000000000000000000000000000000000000000000000000"
old_value = "0x0000000000000000000000000000000000000000000000000000000000000000"

[[kernel_data.public_data_update_requests]]
leaf_slot = "0x0000000000000000000000000000000000000000000000000000000000000000"
new_value = "0x0000000000000000000000000000000000000000000000000000000000000000"
old_value = "0x0000000000000000000000000000000000000000000000000000000000000000"

[[kernel_data.public_data_update_requests]]
leaf_slot = "0x0000000000000000000000000000000000000000000000000000000000000000"
new_value = "0x0000000000000000000000000000000000000000000000000000000000000000"
old_value = "0x0000000000000000000000000000000000000000000000000000000000000000"

[[kernel_data.public_data_update_requests]]
leaf_slot = "0x0000000000000000000000000000000000000000000000000000000000000000"
new_value = "0x0000000000000000000000000000000000000000000000000000000000000000"
old_value = "0x0000000000000000000000000000000000000000000000000000000000000000"

[[kernel_data.public_data_update_requests]]
leaf_slot = "0x0000000000000000000000000000000000000000000000000000000000000000"
new_value = "0x0000000000000000000000000000000000000000000000000000000000000000"
old_value = "0x0000000000000000000000000000000000000000000000000000000000000000"

[[kernel_data.public_data_update_requests]]
leaf_slot = "0x0000000000000000000000000000000000000000000000000000000000000000"
new_value = "0x0000000000000000000000000000000000000000000000000000000000000000"
old_value = "0x0000000000000000000000000000000000000000000000000000000000000000"

[[kernel_data.public_data_update_requests]]
leaf_slot = "0x0000000000000000000000000000000000000000000000000000000000000000"
new_value = "0x0000000000000000000000000000000000000000000000000000000000000000"
old_value = "0x0000000000000000000000000000000000000000000000000000000000000000"

[[kernel_data.public_data_update_requests]]
leaf_slot = "0x0000000000000000000000000000000000000000000000000000000000000000"
new_value = "0x0000000000000000000000000000000000000000000000000000000000000000"
old_value = "0x0000000000000000000000000000000000000000000000000000000000000000"

[[kernel_data.public_data_update_requests]]
leaf_slot = "0x0000000000000000000000000000000000000000000000000000000000000000"
new_value = "0x0000000000000000000000000000000000000000000000000000000000000000"
old_value = "0x0000000000000000000000000000000000000000000000000000000000000000"
