version: '3'
services:
  ethereum:
    image: aztecprotocol/foundry-nightly-de33b6af53005037b463318d2628b5cfcaf3991:latest
    entrypoint: >
      sh -c '
      if [ -n "$FORK_BLOCK_NUMBER" ] && [ -n "$FORK_URL" ]; then
        exec anvil -p 8545 --host 0.0.0.0 --chain-id 31337 --silent --fork-url "$FORK_URL" --fork-block-number "$FORK_BLOCK_NUMBER"
      elif [ -n "$FORK_URL" ]; then
        exec anvil -p 8545 --host 0.0.0.0 --chain-id 31337 --silent --fork-url "$FORK_URL"
      else
        exec anvil -p 8545 --host 0.0.0.0 --chain-id 31337 --silent
      fi'
    ports:
      - '${SANDBOX_ANVIL_PORT:-8545}:8545'

  aztec:
    image: 'aztecprotocol/aztec:${SANDBOX_VERSION:-latest}'
    ports:
      - '${SANDBOX_PXE_PORT:-8080}:8080'
    environment:
      DEBUG: # Loaded from the user shell if explicitly set
      HOST_WORKDIR: '${PWD}' # Loaded from the user shell to show log files absolute path in host
      ETHEREUM_HOST: http://ethereum:8545
      L1_CHAIN_ID: 31337
      ARCHIVER_POLLING_INTERVAL_MS: 50
      P2P_BLOCK_CHECK_INTERVAL_MS: 50
      SEQ_TX_POLLING_INTERVAL_MS: 50
      WS_BLOCK_CHECK_INTERVAL_MS: 50
      PXE_BLOCK_POLLING_INTERVAL_MS: 50
      ARCHIVER_VIEM_POLLING_INTERVAL_MS: 500
    volumes:
      - ./log:/usr/src/yarn-project/aztec/log:rw
