name: deny

on:
  push:
    branches: [master]
    paths: [Cargo.lock, .github/workflows/deny.yml]
  pull_request:
    branches: [master]
    paths: [Cargo.lock, .github/workflows/deny.yml]
  merge_group:

env:
  RUSTFLAGS: -D warnings
  CARGO_TERM_COLOR: always

concurrency: deny-${{ github.head_ref || github.run_id }}

jobs:
  deny:
    name: deny
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: EmbarkStudios/cargo-deny-action@3fd3802e88374d3fe9159b834c7714ec57d6c979
        with:
          command: check all
