name: deny

on:
  push:
    branches: [master]
    paths: [Cargo.lock]
  pull_request:
    branches: [master]
    paths: [Cargo.lock]
  merge_group:

env:
  RUSTFLAGS: -D warnings
  CARGO_TERM_COLOR: always

concurrency: deny-${{ github.head_ref || github.run_id }}

jobs:
  deny:
    name: deny
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: EmbarkStudios/cargo-deny-action@30f817c6f72275c6d54dc744fbca09ebc958599f
        with:
          command: check all
