name: Non-deterministic fuzz tests
on:
  workflow_dispatch:
  schedule:
    # Run nightly at 0300
    - cron: "0 3 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # On regular PRs we run deterministic fuzzing to avoid flaky tests on CI.
  # In the nightly tests we want to explore uncharted territory.
  NOIR_AST_FUZZER_FORCE_NON_DETERMINISTIC: 1
  # Tell arbtest how long it can run the tests for.
  NOIR_AST_FUZZER_FORCE_BUDGET_SECS: 300

jobs:
  ast-fuzz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@1.85.0
        with:
          targets: x86_64-unknown-linux-gnu

      - name: Run tests
        run: cargo test -p noir_ast_fuzzer_fuzz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}