name: Publish documentation

on:
  push:
    branches:
      - master
    paths: [docs/**]
  workflow_dispatch:

jobs:
  publish-docs:
    name: Publish docs
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      - name: Checkout release branch
        uses: actions/checkout@v5

      - uses: taiki-e/install-action@just

      - name: Install Yarn dependencies
        uses: ./.github/actions/setup

      - name: Install deps
        run: just install-js-tools

      - name: Query active docs versions
        run: yarn workspace docs version::stables

      - name: Build docs for deploying
        run: yarn workspaces foreach -Rpt --from docs run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.1
        with:
          publish-dir: "./docs/build"
          production-branch: master
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-github-deployment: false
          deploy-message: "Deploy from GitHub Actions for tag ${{ inputs.noir-ref }}"
          enable-commit-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
