name: Publish Noir Wasm

on:
  workflow_dispatch:

jobs:
  publish-noir-wasm:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-23.05

      - name: Build with Nix
        run: nix build .#noir_wasm

      - name: Discover Build Output Path
        run: echo "BUILD_OUTPUT_PATH=$(readlink -f ./result/noir_wasm)" >> $GITHUB_ENV

      - name: Copy Build Output to Temporary Directory
        run: |
          mkdir temp_publish_dir
          cp -r ${{ env.BUILD_OUTPUT_PATH }}/* temp_publish_dir/
          touch temp_publish_dir/yarn.lock

      - name: Publish to NPM
        working-directory: ./temp_publish_dir
        run: yarn npm publish --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
