name: Pull Request

on:
  merge_group:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  conventional-title:
    name: Validate PR title is Conventional Commit
    runs-on: ubuntu-latest
    steps:
      - name: Check title
        if: github.event_name == 'pull_request_target'
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            chore

  force-push-comment:
    name: Warn external contributors about force-pushing
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != 'noir-lang/noir' }} 
    permissions:
      pull-requests: write
    
    steps:
      - name: Post comment on force pushes
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: ./.github/EXTERNAL_CONTRIBUTOR_PR_COMMENT.md

          