name: Algolia Recrawl
on:
  push:
    branches: [ master ]
  schedule:
    # Run on weekdays at 0900
    - cron: "0 9 * * 1-5"
  workflow_dispatch:

jobs:
  algolia_recrawl:
    name: Algolia Recrawl
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Algolia crawler creation and crawl
        uses: algolia/algoliasearch-crawler-github-actions@v1.1.13
        id: algolia_crawler
        with:
          crawler-user-id: ${{ secrets.CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.CRAWLER_API_KEY }}
          algolia-app-id: ${{ secrets.ALGOLIA_APP_ID }}
          algolia-api-key: ${{ secrets.ALGOLIA_API_KEY }}
          site-url: 'https://noir-lang.org/'
          crawler-name: noir-lang
          override-config: false

      - name: Send an alert in slack
        # Send notifications on scheduled runs if there's a failure.
        if: ${{ failure() && github.event_name == 'schedule' }}
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.ALGOLIA_FAILURE_ALERT_URL }}
          webhook-type: webhook-trigger
          payload: |
            workflow-url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
