name: Rust

on: [push, pull_request]

jobs:
  check_n_test:
    name: cargo check & test
    uses: noir-lang/.github/.github/workflows/rust-test.yml@main

  clippy:
    name: cargo clippy
    uses: noir-lang/.github/.github/workflows/rust-clippy.yml@main

  format:
    name: cargo fmt
    uses: noir-lang/.github/.github/workflows/rust-format.yml@main

  spellcheck:
    name: spellcheck
    uses: noir-lang/.github/.github/workflows/spellcheck.yml@phated/reusable-spellcheck
