
# Start cheap (~1/8th the cost of on demand, ~13th the cost of large GA runners) spot builders
# just for the CI job. These are specced per user and run the entire CI.
# TODO These have a persistent EBS volume that forms a fast-online docker image cache (used by Earthly), meaning
# TODO build steps that ran in previous invocations are quickly ran from cache.
name: Setup Runner and CI
on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      runner_action:
        default: start
        type: string
      runner_type:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      GH_SELF_HOSTED_RUNNER_TOKEN:
        required: true
      BUILD_INSTANCE_SSH_KEY:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

concurrency:
  group: ci-${{ inputs.username }}-${{ inputs.runner_type }}-${{ inputs.runner_action }}
env:
  DOCKERHUB_PASSWORD: "${{ secrets.DOCKERHUB_PASSWORD }}"
  RUN_ID: ${{ github.run_id }}
  RUN_ATTEMPT: ${{ github.run_attempt }}
  USERNAME: ${{ inputs.username }}
  GITHUB_TOKEN: ${{ github.token }}
  GH_SELF_HOSTED_RUNNER_TOKEN: ${{ secrets.GH_SELF_HOSTED_RUNNER_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUILD_INSTANCE_SSH_KEY: ${{ secrets.BUILD_INSTANCE_SSH_KEY }}
  GIT_COMMIT: ${{ github.sha }}
  # kludge until we move away from runners
  WAIT_FOR_RUNNERS: true

jobs:
  start-builder:
    runs-on: ubuntu-latest
    # we want to avoid race conditions when making spot across multiple PRs as we only use one runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Start EC2 runner
        uses: ./.github/ensure-builder
        with:
          runner_action: ${{ inputs.runner_action }}
          runner_type: ${{ inputs.runner_type }}
