name: Spellcheck

on: [pull_request]

# This will cancel previous runs when a branch or PR is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  code:
    name: Code
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Check spelling
        uses: streetsidesoftware/cspell-action@v2
        with:
          strict: false # Do not fail, if a spelling mistake is found (This can be annoying for contributors)
          incremental_files_only: true # Run this action on files which have changed in PR
          files: |
            **/*.{md,rs}

  docs:
    name: Documentation
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Check spelling
        uses: streetsidesoftware/cspell-action@v2
        with:
          strict: true # Documentation has higher standards for correctness.
          incremental_files_only: true # Run this action on files which have changed in PR
          files: |
            ./docs/**/*.md
